name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        run-mode: ["development", "production"]
        phantom: ["phantom", "no phantom"]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install PhantomJS plugin
      run: npm install --no-save website-scraper-phantom
      if: ${{ matrix.phantom == 'phantom' }}
    
    - name: Set up & build frontend
      run: |
        npm install --no-save
        npm run build
      working-directory: Collect/public/frontend

    # This makes sure that package.json and package-lock.json are synchronized correctly
    # It also makes sure that the latest build of the frontend is committed
    - name: Make sure no files changed
      run: |
        if [[ `git status --porcelain` ]]; then
            git status
            git diff .
            echo "::error::Tracked files changed after installing dependencies and building the frontend. This usually happens when package.json and package-lock.json are not in sync (run npm install and commit to fix OR build the frontend)"
            exit 1
        fi


    - name: Start server and try a request
      run: |
       cd Collect
       npm install
      
       sudo npm run start ${{ matrix.run-mode }} &
       sleep 10
       
       curl -L http://localhost:80
